### ISSUE TITLE
Does this library support diffing recursively?

### ISSUE THREAD

**Issue by JanisE** [DusanKasan/Knapsack#49] opened 2018-04-09 12:12 UTC
Are multi-dimension arrays supported? E.g., PHP's array_diff would return "Array to string conversion" error if any of the compared arrays contain a (sub-)array.

**Comment by DusanKasan** [comment] 2018-04-09 12:52
Hi, you can see the implementation [here](https://github.com/DusanKasan/Knapsack/blob/master/src/collection_functions.php#L1274), it's pretty straightforward. I'm pretty sure it will not have the drawback you are describing since it's calling in_array internally. Does this answer your question?

**Comment by JanisE** [comment] 2018-04-09 19:57
Thank you! Yes, it does answer the question, although it would probably be useful to give some explanation also in the docs.

So, without actually testing, it seems to me that Knapsack's `diff` would not throw on array elements as `array_diff` would, but it also wouldn't compare the array recursively by its contents – the array would match an array of the other collection only if it would be the same array (explicitly put in there by reference).

**Comment by DusanKasan** [comment] 2018-04-09 20:50
in_array works like [this](https://3v4l.org/EpA6Z) which means PHP arrays are compared with respect to nested elements. Am I missing something here?

**Comment by JanisE** [comment] 2018-04-10 07:01
No, but I have had a wrong understanding how `in_array` works. Thanks!

**Comment by DusanKasan** [comment] 2018-04-10 07:32
No problem :) Closing this as the issue is resolved.

**Closed as completed by DusanKasan** 2018-04-10 07:32 UTC
